name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - name: Install Dependencies
      run: cd docs && npm install
    - name: Build
      run: cd docs && npm run build
