name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - name: Install Dependencies
      working-directory: ./docs
      run: npm install
    - name: Build
      working-directory: ./docs
      run: npm run build
